server:
  port: 9011
spring:
  application:
    name: tensquare-manager
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/ #eureka服务地址
  instance:
    prefer-ip-address: true
zuul:
  routes:
    tensquare-base:
      path: /base/** # 访问的路径，如果访问的路径是以base开头的，那么就会跳转到tensquare-base微服务   配置请求URL的请求规则
      serviceId: tensquare-base #指定跳转的服务名称. 指定Eureka注册中心中的服务id
