server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://121.36.25.190:3306/tensquare_base?characterEncoding=UTF8
  jpa:
    database: mysql
    show-sql: true