spring:
  application:
    name: tensquare-friend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://121.36.25.190:3306/tensquare_friend?characterEncoding=utf-8
  jpa:
    show-sql: true
    database: mysql
server:
  port: 9010
jwt:
  config:
    key: itcast
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true # 此处配置项的含义是,部署线上时,模块之间可以跨域访问

