server:
  port: 9002
spring:
  application:
    name: tensquare-recruit #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.36.25.190:3306/tensquare_article?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
